import { Metadata } from 'next';
import styles from './page.module.css';
import FlowCharts from './components/FlowCharts';
import NavbarDashboard from './components/NavbarDashboard';
import { createClient } from '@/utils/supabase/server';
import { cookies } from 'next/headers';

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
};

const Dashboard = async () => {
  const cookieStore = cookies();
  const supabase = createClient(cookieStore);

  const user = await supabase.auth.getUser();

  return (
    <main className={styles.main}>
      <NavbarDashboard
        userProfile={user.data.user?.user_metadata.avatar_url as string}
      />
      <FlowCharts />
    </main>
  );
};

export default Dashboard;
