import { Metadata } from "next";
import styles from "./page.module.css";
import FlowCharts from "./components/FlowCharts";
import NavbarDashboard from "./components/NavbarDashboard";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const Dashboard = () => {
  return (
    <main className={styles.main}> 
      <NavbarDashboard />
      <FlowCharts />
    </main>
  )
}

export default Dashboard