import { Metadata } from 'next';
import FlowCharts from './components/FlowCharts';

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
};

const Dashboard = async () => {
  return <FlowCharts />;
};

export default Dashboard;
